# Generated by Django 5.1.8 on 2025-08-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Nome do administrador: ')),
                ('telephone', models.CharField(max_length=13, null=True, verbose_name='Telefone do administrador: ')),
                ('cpf', models.CharField(max_length=14, null=True, verbose_name='CPF do administrador: ')),
                ('password', models.CharField(max_length=100, null=True, verbose_name='Senha do administrador: ')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Nome do cliente: ')),
                ('telephone', models.CharField(max_length=13, null=True, verbose_name='Telefone do cliente: ')),
                ('cpf', models.CharField(max_length=14, null=True, verbose_name='CPF do cliente: ')),
                ('password', models.CharField(max_length=100, null=True, verbose_name='Senha do cliente: ')),
                ('address', models.CharField(max_length=100, null=True, verbose_name='Endereço do cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Nome do drink: ')),
                ('size', models.CharField(max_length=50, null=True, verbose_name='Tamanho do drink: ')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Preço do drink: ')),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Nome da pizza: ')),
                ('ingredients', models.CharField(max_length=300, null=True, verbose_name='Descrição da pizza: ')),
                ('size', models.CharField(max_length=50, null=True, verbose_name='Tamanho da pizza: ')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Preço da pizza: ')),
            ],
        ),
    ]
