# Generated by Django 5.1.8 on 2025-08-18 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tamanhos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanhos_nome', models.CharField(choices=[('Pequena', '4 pedaços'), ('Pequena', '6 pedaços'), ('Média', '8 pedaços'), ('Grande', '10 pedaços'), ('Gigante', '12 pedaços')], max_length=50, verbose_name='Tamanho da pizza: ')),
            ],
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='size',
        ),
        migrations.AddField(
            model_name='pizza',
            name='class_choices',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bd.tamanhos', verbose_name='Tamanho da pizza: '),
        ),
    ]
