# Generated by Django 5.1.8 on 2025-08-11 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
    ]
