# Generated by Django 5.1.5 on 2025-08-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.AddField(
            model_name='admin',
            name='telephone',
            field=models.CharField(max_length=13, null=True, verbose_name='Telefone do administrador: '),
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=100, null=True, verbose_name='Endereço do cliente'),
        ),
        migrations.AddField(
            model_name='customer',
            name='telephone',
            field=models.CharField(max_length=13, null=True, verbose_name='Telefone do cliente: '),
        ),
    ]
