# Generated by Django 5.1.8 on 2025-08-18 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0002_tamanhos_remove_pizza_size_pizza_class_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volumes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volumes_nome', models.CharField(choices=[('500ml', '500ml'), ('1L', '1L'), ('1.5L', '1.5L'), ('2L', '2L')], max_length=50, verbose_name='Volume do drink: ')),
            ],
        ),
        migrations.RemoveField(
            model_name='drink',
            name='size',
        ),
        migrations.AlterField(
            model_name='tamanhos',
            name='tamanhos_nome',
            field=models.CharField(choices=[('Mini', '4 pedaços'), ('Pequena', '6 pedaços'), ('Média', '8 pedaços'), ('Grande', '10 pedaços'), ('Gigante', '12 pedaços')], max_length=50, verbose_name='Tamanho da pizza: '),
        ),
        migrations.AddField(
            model_name='drink',
            name='class_choices',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bd.volumes', verbose_name='Volume do drink: '),
        ),
    ]
