# Generated by Django 5.1.8 on 2025-08-18 12:56

import bd.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0003_volumes_remove_drink_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[bd.models.validate_password], verbose_name='Endereço do cliente'),
        ),
    ]
