# Generated by Django 5.1.8 on 2025-08-25 10:50

import bd.validate
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0005_alter_admin_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='cpf',
            field=models.CharField(max_length=14, null=True, validators=[bd.validate.cpf_validate], verbose_name='CPF do administrador: '),
        ),
        migrations.AlterField(
            model_name='admin',
            name='telephone',
            field=models.CharField(max_length=13, null=True, validators=[bd.validate.telefone_validate], verbose_name='Telefone do administrador: '),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cpf',
            field=models.CharField(max_length=14, null=True, validators=[bd.validate.cpf_validate], verbose_name='CPF do cliente: '),
        ),
        migrations.AlterField(
            model_name='customer',
            name='telephone',
            field=models.CharField(max_length=13, null=True, validators=[bd.validate.telefone_validate], verbose_name='Telefone do cliente: '),
        ),
    ]
